########################################################
#@@@-------------GENERATED BY AUTO_MAKE-------------@@@#
#@@                                                  @@#
#@  https://github.com/kagestonedragon/auto_make_php  @#
########################################################

NAME = corewar

GCC = gcc

GCC_FLAGS = 

OBJ_PATH = objects/

INCLUDE_INCLUDES = includes/

SOURCES_PATH = sources/
SOURCES_MISCELLANEOUS_PATH = sources/miscellaneous/
SOURCES_MISCELLANEOUS_IDENTIFICATION_PATH = sources/miscellaneous/identification/
SOURCES_MISCELLANEOUS_CONVERTING_PATH = sources/miscellaneous/converting/
SOURCES_MISCELLANEOUS_DEBUG_PATH = sources/miscellaneous/debug/
SOURCES_MISCELLANEOUS_ERROR_MANAGEMENT_PATH = sources/miscellaneous/error_management/
SOURCES_PARSING_PATH = sources/parsing/
SOURCES_FILES = \
			main.c
SOURCES_MISCELLANEOUS_IDENTIFICATION_FILES = \
			is_cor_file.c\
			is_integer.c
SOURCES_MISCELLANEOUS_CONVERTING_FILES = \
			bytecode_to_int32.c
SOURCES_MISCELLANEOUS_DEBUG_FILES = \
			debug_options.c\
			debug_champions.c
SOURCES_MISCELLANEOUS_ERROR_MANAGEMENT_FILES = \
			print_help.c\
			terminate.c
SOURCES_PARSING_FILES = \
			initialization.c\
			read_binary.c\
			champions.c\
			options.c

OBJ_SOURCES_CORE = $(addprefix $(OBJ_PATH), $(SOURCES_FILES:.c=.o))
OBJ_SOURCES_MISCELLANEOUS_CORE = $(addprefix $(OBJ_PATH), $(SOURCES_MISCELLANEOUS_FILES:.c=.o))
OBJ_SOURCES_MISCELLANEOUS_IDENTIFICATION_CORE = $(addprefix $(OBJ_PATH), $(SOURCES_MISCELLANEOUS_IDENTIFICATION_FILES:.c=.o))
OBJ_SOURCES_MISCELLANEOUS_CONVERTING_CORE = $(addprefix $(OBJ_PATH), $(SOURCES_MISCELLANEOUS_CONVERTING_FILES:.c=.o))
OBJ_SOURCES_MISCELLANEOUS_DEBUG_CORE = $(addprefix $(OBJ_PATH), $(SOURCES_MISCELLANEOUS_DEBUG_FILES:.c=.o))
OBJ_SOURCES_MISCELLANEOUS_ERROR_MANAGEMENT_CORE = $(addprefix $(OBJ_PATH), $(SOURCES_MISCELLANEOUS_ERROR_MANAGEMENT_FILES:.c=.o))
OBJ_SOURCES_PARSING_CORE = $(addprefix $(OBJ_PATH), $(SOURCES_PARSING_FILES:.c=.o))

OBJECTS = $(OBJ_SOURCES_CORE) $(OBJ_SOURCES_MISCELLANEOUS_CORE) $(OBJ_SOURCES_MISCELLANEOUS_IDENTIFICATION_CORE) $(OBJ_SOURCES_MISCELLANEOUS_CONVERTING_CORE) $(OBJ_SOURCES_MISCELLANEOUS_DEBUG_CORE) $(OBJ_SOURCES_MISCELLANEOUS_ERROR_MANAGEMENT_CORE) $(OBJ_SOURCES_PARSING_CORE) 

all: $(NAME)

$(NAME): $(OBJECTS)
		make -C dependencies/libft
		@($(GCC) $(GCC_FLAGS) -o $(NAME) $(OBJECTS) -L dependencies/libft/ -lft)
		@(echo "^[[0;92m"$(NAME) "was created!^[[0;0m")

clean:
		make clean -C dependencies/libft
		@(/bin/rm -rf $(OBJ_PATH))
		@(echo "^[[0;91mAll object files have been deleted!^[[0;0m")

fclean: clean
		make fclean -C dependencies/libft
		@(/bin/rm -f $(NAME))
		@(echo "^[[0;91m"$(NAME) "has been deleted!^[[0;0m")

re: fclean all

objects:
		@(mkdir $(OBJ_PATH))

objects/%.o: $(SOURCES_PATH)%.c | objects
		@($(GCC) $(GCC_FLAGS) -I $(INCLUDE_INCLUDES) -c $< -o $@)
		(echo "^[[0;93m"$< "->" $@"^[[0;0m")

objects/%.o: $(SOURCES_MISCELLANEOUS_PATH)%.c | objects
		@($(GCC) $(GCC_FLAGS) -I $(INCLUDE_INCLUDES) -c $< -o $@)
		(echo "^[[0;93m"$< "->" $@"^[[0;0m")

objects/%.o: $(SOURCES_MISCELLANEOUS_IDENTIFICATION_PATH)%.c | objects
		@($(GCC) $(GCC_FLAGS) -I $(INCLUDE_INCLUDES) -c $< -o $@)
		(echo "^[[0;93m"$< "->" $@"^[[0;0m")

objects/%.o: $(SOURCES_MISCELLANEOUS_CONVERTING_PATH)%.c | objects
		@($(GCC) $(GCC_FLAGS) -I $(INCLUDE_INCLUDES) -c $< -o $@)
		(echo "^[[0;93m"$< "->" $@"^[[0;0m")

objects/%.o: $(SOURCES_MISCELLANEOUS_DEBUG_PATH)%.c | objects
		@($(GCC) $(GCC_FLAGS) -I $(INCLUDE_INCLUDES) -c $< -o $@)
		(echo "^[[0;93m"$< "->" $@"^[[0;0m")

objects/%.o: $(SOURCES_MISCELLANEOUS_ERROR_MANAGEMENT_PATH)%.c | objects
		@($(GCC) $(GCC_FLAGS) -I $(INCLUDE_INCLUDES) -c $< -o $@)
		(echo "^[[0;93m"$< "->" $@"^[[0;0m")

objects/%.o: $(SOURCES_PARSING_PATH)%.c | objects
		@($(GCC) $(GCC_FLAGS) -I $(INCLUDE_INCLUDES) -c $< -o $@)
		(echo "^[[0;93m"$< "->" $@"^[[0;0m")

