########################################################
#@@@-------------GENERATED BY AUTO_MAKE-------------@@@#
#@@                                                  @@#
#@    https://github.com/kagestonedragon/auto_make    @#
########################################################

NAME = auto_make

GCC = gcc

GCC_FLAGS = -Wall -Wextra -Werror

OBJ_PATH = objects/

INCLUDES_INCLUDE = includes/

SOURCES_PATH = sources/

SOURCES_FILES = \
		create_makefile.c \
		errors.c \
		get_variables.c \
		information.c \
		main.c \
		parsing.c \
		parsing_directories.c \
		parsing_files.c 

OBJ_SOURCES_CORE = $(addprefix $(OBJ_PATH), $(SOURCES_FILES:.c=.o))

OBJECTS = $(OBJ_SOURCES_CORE) 

all: $(NAME)

$(NAME): $(OBJECTS)
		@($(GCC) $(GCC_FLAGS) -o $(NAME) $(OBJECTS))
		@(echo "[0;92m"$(NAME) "was created![0;0m")

clean:
		@(/bin/rm -rf $(OBJ_PATH))
		@(echo "[0;91mAll object files have been deleted![0;0m")

fclean: clean
		@(/bin/rm -f $(NAME))
		@(echo "[0;91m"$(NAME) "has been deleted![0;0m")

re: fclean all

objects:
		@(mkdir $(OBJ_PATH))

objects/%.o: $(SOURCES_PATH)%.c | objects
		@($(GCC) $(GCC_FLAGS) -I $(INCLUDES_INCLUDE) -c $< -o $@)
		@(echo "[0;93m"$< "->" $@"[0;0m")
